Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"

  config.vm.network "forwarded_port", guest: 80, host: 8080


  config.vm.synced_folder "../utn-devops-app", "/var/www/utn-devops-app"

  config.vm.provision "shell", path: "provision.sh"

end
